const mongoose =  require("mongoose");
const Property = mongoose.model("Property");
var cloudinary = require('cloudinary').v2;


cloudinary.config({
    cloud_name: 'dr2z10vvr',
    api_key: '659977896451491',
    api_secret: 'Eamdv5FN6K5cGasCXjJmQCvgY00'
});


class CmsService{
    async getPoperties(enabled,featured){
        if(enabled){
            return Property.find({enabled:true}).lean(true).limit(20);
        }
        else
        {
            return Property.find({}).lean(true).limit(20)
        }
    }
    async changeUrl(){

        let property = Property.findOne({enabled:true}).lean(true)
        return property;

        /*cloudinary.uploader.upload('https://www.filepicker.io/api/file/7n025TxSAGPJ5ITwsMSU', { tags: 'property' }, function (err, image) {
            console.log()
            console.log("** File Upload");
            if (err) { console.warn(err); }
            console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
            console.log("* " + image.public_id);
            console.log("* " + image.url);
        });*/
    }
}

module.exports = new CmsService();
